# Generated by Django 4.1.4 on 2023-01-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='nperson',
        ),
    ]
